
#define ETHERNET_CONNECTED_BIT BIT0
#define ETHERNET_DISCONNECT_BIT BIT1
#define GOT_IP_BIT BIT2
#define CLIENT_RECIEVED_BIT BIT3
#define SPIFFS_OPERATION_DONE BIT4
#define DEVICE_CONFIG_BIT BIT5
#define LOAD_MAPPING_BIT BIT6
#define FLASH_FLUSHING_BIT BIT7