
#define ETHERNET_CONNECTED_BIT BIT0
#define ETHERNET_DISCONNECT_BIT BIT1
#define GOT_IP_BIT BIT2
#define CLIENT_RECIEVED_BIT BIT3
#define SPIFFS_OPERATION_DONE BIT4
#define DEVICE_CONFIG_BIT BIT5
#define LOAD_MAPPING_BIT BIT6
#define FLASH_FLUSHING_BIT BIT7
#define HTML_FILE_BIT BIT8
// Fingerprint event bits
#define FINGERPRINT_IMG_EVENT_BIT 1
#define FINGERPRINT_DONE_EVENT_BIT 2
#define FINGERPRINT_ERROR_EVENT_BIT 3