char loginPage[] = 
"<!DOCTYPE html>\n"
"<html>\n"
"  <head>\n"
"    <title>Login Page</title>\n"
"    <style>\n"
"      /* Simple CSS for centering the form on the page */\n"
"      body {\n"
"        display: flex;\n"
"        justify-content: center;\n"
"        align-items: center;\n"
"        height: 100vh;\n"
"      }\n"
"\n"
"      form {\n"
"        width: 300px;\n"
"        padding: 20px;\n"
"        background-color: #f5f5f5;\n"
"        border-radius: 5px;\n"
"        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\n"
"      }\n"
"\n"
"      label {\n"
"        display: block;\n"
"        margin-bottom: 10px;\n"
"      }\n"
"\n"
"      input[type=\"text\"],\n"
"      input[type=\"password\"] {\n"
"        width: 100%;\n"
"        padding: 10px;\n"
"        border-radius: 3px;\n"
"        border: none;\n"
"        margin-bottom: 20px;\n"
"        box-sizing: border-box;\n"
"      }\n"
"\n"
"      button[type=\"submit\"] {\n"
"        background-color: #008cba;\n"
"        border: none;\n"
"        color: white;\n"
"        padding: 10px 20px;\n"
"        border-radius: 3px;\n"
"        cursor: pointer;\n"
"      }\n"
"\n"
"      button[type=\"submit\"]:hover {\n"
"        background-color: #006a8e;\n"
"      }\n"
"    </style>\n"
"  </head>\n"
"\n"
"  <body>\n"
"    <form onsubmit=\"return submitForm(event)\">\n"
"      <h1>Login</h1>\n"
"      <label>Username:</label>\n"
"      <input type=\"text\" id=\"username\" required>\n"
"\n"
"      <label>Password:</label>\n"
"      <input type=\"password\" id=\"password\" required>\n"
"\n"
"      <button type=\"submit\">Submit</button>\n"
"    </form>\n"
"\n"
"    <script>\n"
"      // Function to submit the login form\n"
"      function submitForm(event) {\n"
"        // Prevent the default form submission behavior\n"
"        event.preventDefault();\n"
"\n"
"        // Get the values from the form fields\n"
"        const username = document.getElementById(\"username\").value;\n"
"        const password = document.getElementById(\"password\").value;\n"
"\n"
"        // Send a POST request to the server with the login information\n"
"        fetch(\"http://192.168.50.148/getData\", {\n"
"          method: \"POST\",\n"
"          headers: {\n"
"            \"Content-Type\": \"application/json\",\n"
"          },\n"
"          body: JSON.stringify({ username, password }),\n"
"        })\n"
"          .then((response) => {\n"
"            // If the response status is ok, redirect to the dashboard\n"
"            if (response.ok) {\n"
"              window.location.href = \"http://192.168.50.148/dashboard\";\n"
"            } else {\n"
"              // Otherwise, display an error message\n"
"              alert(\"Invalid username or password\");\n"
"            }\n"
"          })\n"
"          .catch((error) => {\n"
"            console.error(error);\n"
"          });\n"
"      }\n"
"    </script>\n"
"  </body>\n"
"</html>\n"
;

char dashboard [] = 
"<!DOCTYPE html>\n"
"<html>\n"
"\n"
"<head>\n"
"  <title>Biometric Attendance System</title>\n"
"  <style>\n"
"    body {\n"
"      font-family: Arial, sans-serif;\n"
"      margin: 0;\n"
"      padding: 0;\n"
"    }\n"
"\n"
"    #header {\n"
"      background-color: #333;\n"
"      color: white;\n"
"      padding: 10px;\n"
"    }\n"
"\n"
"    #menu {\n"
"      background-color: #f2f2f2;\n"
"      height: 100%;\n"
"      padding: 10px;\n"
"      width: 200px;\n"
"      position: fixed;\n"
"      top: 101px;\n"
"      left: 0;\n"
"    }\n"
"\n"
"    #menu ul {\n"
"      list-style-type: none;\n"
"      margin: 0;\n"
"      padding: 0;\n"
"    }\n"
"\n"
"    #menu li {\n"
"      padding: 10px;\n"
"      border-bottom: 1px solid #ccc;\n"
"      cursor: pointer;\n"
"    }\n"
"\n"
"    #menu li:hover {\n"
"      background-color: #ddd;\n"
"    }\n"
"\n"
"    #data {\n"
"      margin-left: 220px;\n"
"      margin-top: 80px;\n"
"      padding: 10px;\n"
"    }\n"
"  </style>\n"
"</head>\n"
"\n"
"<body>\n"
"  <div id=\"header\">\n"
"    <h1>SWH-Biometric Attendance System</h1>\n"
"  </div>\n"
"  <div id=\"menu\">\n"
"    <ul>\n"
"      <li onclick=\"getData('network')\">Network</li>\n"
"      <li onclick=\"getData('device')\">Device Configurations</li>\n"
"      <li onclick=\"getData('enrollment')\">Enrollment</li>\n"
"      <li onclick=\"getData('datetime')\">Date and Time</li>\n"
"      <li onclick=\"getData('logout')\">Logout</li>\n"
"    </ul>\n"
"  </div>\n"
"  <div id=\"data\"></div>\n"
"\n"
"  <script>\n"
"    function getData(setting) {\n"
"      const url = `http://192.168.50.148/${setting}`;\n"
"      const login_redirect = `http://192.168.50.148/login`;\n"
"\n"
"      if (setting === \"device\") {\n"
"        const formHtml = `\n"
"        <form id=\"device-form\" style=\"display: flex; flex-direction: column; align-items: center; margin-top: 50px;\">\n"
"  <div style=\"display: flex; flex-direction: column; align-items: center; margin-bottom: 10px;\">\n"
"    <label for=\"device_id\" style=\"margin-right: 10px;\">Device ID:</label>\n"
"    <input type=\"text\" id=\"device_id\" name=\"device_id\" required style=\"padding: 8px; border: none; border-bottom: 2px solid #ddd; width: 100%; margin-bottom: 10px; text-align: center\">\n"
"  </div>\n"
"  <div style=\"display: flex; flex-direction: column; align-items: center; margin-bottom: 10px;\">\n"
"    <label for=\"auth_token\" style=\"margin-right: 10px;\">Auth Token:</label>\n"
"    <input type=\"text\" id=\"auth_token\" name=\"auth_token\" required style=\"padding: 8px; border: none; border-bottom: 2px solid #ddd; width: 100%; margin-bottom: 10px; text-align: center\">\n"
"  </div>\n"
"  <div style=\"display: flex; flex-direction: column; align-items: center; margin-bottom: 10px;\">\n"
"    <label for=\"device_location\" style=\"margin-right: 10px;\">Device Location:</label>\n"
"    <input type=\"text\" id=\"device_location\" name=\"device_location\" required style=\"padding: 8px; border: none; border-bottom: 2px solid #ddd; width: 100%; margin-bottom: 10px; text-align: center\">\n"
"  </div>\n"
"  <div style=\"display: flex; flex-direction: column; align-items: center; margin-bottom: 10px;\">\n"
"    <label for=\"location_id\" style=\"margin-right: 10px;\">Location ID:</label>\n"
"    <input type=\"text\" id=\"location_id\" name=\"location_id\" required style=\"padding: 8px; border: none; border-bottom: 2px solid #ddd; width: 100%; margin-bottom: 10px;text-align: center \">\n"
"  </div>\n"
"  <button type=\"submit\" style=\"padding: 10px; background-color: #333; color: white; border: none; border-radius: 5px; cursor: pointer;\">Save</button>\n"
"</form>\n"
"`;\n"
"\n"
"        document.getElementById('data').innerHTML = formHtml;\n"
"        document.getElementById('device-form').addEventListener('submit', submitDeviceForm);\n"
"\n"
"      }\n"
"      else if (setting == \"datetime\") {\n"
"        const formHtml = `\n"
"        <form id=\"datetime-form\" style=\"margin: auto; width: 50%; padding: 20px; border: 1px solid #ddd; border-radius: 5px;\">\n"
"        <label for=\"date\">Date:</label>\n"
"        <input type=\"date\" id=\"date\" name=\"date\" style=\"margin-bottom: 10px; padding: 5px; border-radius: 5px; border: 1px solid #ccc;\"><br>\n"
"        <label for=\"time\">Time:</label>\n"
"        <input type=\"time\" id=\"time\" name=\"time\" style=\"margin-bottom: 10px; padding: 5px; border-radius: 5px; border: 1px solid #ccc;\"><br>\n"
"        <button type=\"submit\" style=\"padding: 10px; background-color: #333; color: white; border: none; border-radius: 5px; cursor: pointer;\">Save</button>\n"
"      </form>\n"
"            `;\n"
"          \n"
"          document.getElementById('data').innerHTML = formHtml;\n"
"          document.getElementById('datetime-form').addEventListener('submit', submitDatetimeForm);\n"
"      }\n"
"      else if (setting == \"logout\") {\n"
"        fetch(\"http://192.168.50.148/logout\", {\n"
"          method: \"GET\",\n"
"          headers: {\n"
"            \"Content-Type\": \"application/json\",\n"
"          }\n"
"        }).then((response) => {\n"
"          // If the response status is ok, redirect to the dashboard\n"
"          if (response.ok) {\n"
"            window.location.href = login_redirect;\n"
"\n"
"\n"
"          }\n"
"        })\n"
"\n"
"\n"
"      }\n"
"      else if (setting == \"network\") {\n"
"      const formHtml = `<form id=\"my-form\" style=\"display: flex; flex-direction: column; align-items: center;\">\n"
"  <label for=\"ip\" style=\"margin-bottom: 10px;\">IP Address:</label>\n"
"  <input type=\"text\" id=\"ip\" name=\"ip\" readonly style=\"padding: 5px; border: none; border-radius: 5px; background-color: #f2f2f2; margin-bottom: 10px; text-align: center\"><br>\n"
"  <label for=\"mac\" style=\"margin-bottom: 10px;\">MAC Address:</label>\n"
"  <input type=\"text\" id=\"mac\" name=\"mac\" readonly style=\"padding: 5px; border: none; border-radius: 5px; background-color: #f2f2f2; margin-bottom: 10px; text-align: center\"><br>\n"
"</form>\n"
"`;\n"
"document.getElementById('data').innerHTML = formHtml;\n"
"getNetworkData();\n"
"\n"
"\n"
"\n"
"      }\n"
"\n"
"      else {\n"
"        fetch(url)\n"
"          .then(response => response.text())\n"
"          .then(data => {\n"
"            document.getElementById('data').textContent = data;\n"
"          })\n"
"          .catch(error => console.error(error));\n"
"      }\n"
"    }\n"
"\n"
"    function submitDatetimeForm(e){\n"
"      e.preventDefault();\n"
"      const date = document.getElementById('date').value;\n"
"      const time = document.getElementById('time').value;\n"
"\n"
"      const datetime = `${date} ${time}`;\n"
"      const url = 'http://192.168.50.148/dateTime';\n"
"\n"
"      fetch(url, {\n"
"        method: 'POST',\n"
"        body: JSON.stringify({date: date , time: time}),\n"
"        headers: {\n"
"          'Content-Type': 'application/json'\n"
"        }\n"
"      })\n"
"    }\n"
"    function submitDeviceForm(e){\n"
"      e.preventDefault();\n"
"      const d_id = document.getElementById('device_id').value;\n"
"      const auth = document.getElementById('auth_token').value;\n"
"      const d_location = document.getElementById('device_location').value;\n"
"      const l_id = document.getElementById('location_id').value;\n"
"\n"
"\n"
"      const url = 'http://192.168.50.148/getDeviceConfigs';\n"
"\n"
"      fetch(url, {\n"
"        method: 'POST',\n"
"        body: JSON.stringify({\n"
"          device_id: d_id , \n"
"          auth_token: auth , \n"
"          device_location: d_location , \n"
"          location_id: l_id}),\n"
"        headers: {\n"
"          'Content-Type': 'application/json'\n"
"        }\n"
"      })\n"
"    }\n"
"\n"
"  function getNetworkData(){\n"
"    fetch('http://192.168.50.148/network')\n"
"    .then(response => response.json())\n"
"    .then(data => {\n"
"      document.getElementById('ip').value = data.ip;\n"
"      document.getElementById('mac').value = data.mac;\n"
"    });\n"
"  }\n"
"  </script>\n"
"</body>\n"
"\n"
"</html>"
;

char enrollmentPage[] = 
"<!DOCTYPE html>\n"
"<html>\n"
"  <head>\n"
"    <title>Student Enrollment Form</title>\n"
"    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n"
"    <script>\n"
"      $(document).ready(function() {\n"
"        // Get Student Data button click handler\n"
"        $('#get-student-data').on('click', function() {\n"
"          // Make an AJAX request to retrieve the student data from the server\n"
"          $.getJSON('http://192.168.50.148/getStdData', function(data) {\n"
"            // Clear any existing rows from the table\n"
"            $('#student-table tbody').empty();\n"
"            \n"
"            // Loop through each student object and add a new row to the table\n"
"            $.each(data, function(index, student) {\n"
"              var row = $('<tr>').appendTo('#student-table tbody');\n"
"              $('<td>').text(student.id).appendTo(row);\n"
"              $('<td>').text(student.name).appendTo(row);\n"
"              $('<td>').text(student.user_name).appendTo(row);\n"
"              $('<td>').html('<button type=\"button\" class=\"enroll-button\">Enroll</button>').appendTo(row);\n"
"            });\n"
"          });\n"
"        });\n"
"        \n"
"        // Enroll button click handler\n"
"        $(document).on('click', '.enroll-button', function() {\n"
"          var vuId = $(this).closest('tr').find('td:nth-child(3)').text();\n"
"          \n"
"          // Make an AJAX request to enroll the student using the vu_id\n"
"          $.ajax({\n"
"            url: 'http://192.168.50.148/enrollStudent',\n"
"            method: 'POST',\n"
"            data: JSON.stringify({ vu_id: vuId }),\n"
"            contentType: \"application/json\",\n"
"            success: function(response) {\n"
"              // Handle the success response\n"
"              console.log('Enrollment successful!');\n"
"            },\n"
"            error: function(xhr, status, error) {\n"
"              // Handle the error response\n"
"              console.error('Enrollment failed:', error);\n"
"            }\n"
"          });\n"
"        });\n"
"      });\n"
"    </script>\n"
"    <style>\n"
"      table {\n"
"        border-collapse: collapse;\n"
"        width: 100%;\n"
"      }\n"
"      th, td {\n"
"        text-align: left;\n"
"        padding: 8px;\n"
"      }\n"
"      th {\n"
"        background-color: #333;\n"
"        color: white;\n"
"      }\n"
"      tr:nth-child(even) {\n"
"        background-color: #f2f2f2;\n"
"      }\n"
"      button {\n"
"        padding: 6px;\n"
"        background-color: #333;\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 5px;\n"
"        cursor: pointer;\n"
"      }\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"    <h1>Student Enrollment Form</h1>\n"
"    <button id=\"get-student-data\">Get Student Data</button>\n"
"    <table id=\"student-table\">\n"
"      <thead>\n"
"        <tr>\n"
"          <th>ID</th>\n"
"          <th>Name</th>\n"
"          <th>Enroll</th>\n"
"        </tr>\n"
"      </thead>\n"
"      <tbody>\n"
"        <!-- Rows will be added dynamically -->\n"
"      </tbody>\n"
"    </table>\n"
"  </body>\n"
"</html>\n"
;
