char loginPage[] = 
"<!DOCTYPE html>\n"
"<html>\n"
"  <head>\n"
"    <title>Login Page</title>\n"
"    <style>\n"
"      /* Simple CSS for centering the form on the page */\n"
"      body {\n"
"        display: flex;\n"
"        justify-content: center;\n"
"        align-items: center;\n"
"        height: 100vh;\n"
"      }\n"
"\n"
"      form {\n"
"        width: 300px;\n"
"        padding: 20px;\n"
"        background-color: #f5f5f5;\n"
"        border-radius: 5px;\n"
"        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\n"
"      }\n"
"\n"
"      label {\n"
"        display: block;\n"
"        margin-bottom: 10px;\n"
"      }\n"
"\n"
"      input[type=\"text\"],\n"
"      input[type=\"password\"] {\n"
"        width: 100%;\n"
"        padding: 10px;\n"
"        border-radius: 3px;\n"
"        border: none;\n"
"        margin-bottom: 20px;\n"
"        box-sizing: border-box;\n"
"      }\n"
"\n"
"      button[type=\"submit\"] {\n"
"        background-color: #008cba;\n"
"        border: none;\n"
"        color: white;\n"
"        padding: 10px 20px;\n"
"        border-radius: 3px;\n"
"        cursor: pointer;\n"
"      }\n"
"\n"
"      button[type=\"submit\"]:hover {\n"
"        background-color: #006a8e;\n"
"      }\n"
"    </style>\n"
"  </head>\n"
"\n"
"  <body>\n"
"    <form onsubmit=\"return submitForm(event)\">\n"
"      <h1>Login</h1>\n"
"      <label>Username:</label>\n"
"      <input type=\"text\" id=\"username\" required>\n"
"\n"
"      <label>Password:</label>\n"
"      <input type=\"password\" id=\"password\" required>\n"
"\n"
"      <button type=\"submit\">Submit</button>\n"
"    </form>\n"
"\n"
"    <script>\n"
"      // Function to submit the login form\n"
"      function submitForm(event) {\n"
"        // Prevent the default form submission behavior\n"
"        event.preventDefault();\n"
"\n"
"        // Get the values from the form fields\n"
"        const username = document.getElementById(\"username\").value;\n"
"        const password = document.getElementById(\"password\").value;\n"
"\n"
"        // Send a POST request to the server with the login information\n"
"        fetch(\"http://192.168.50.140/getData\", {\n"
"          method: \"POST\",\n"
"          headers: {\n"
"            \"Content-Type\": \"application/json\",\n"
"          },\n"
"          body: JSON.stringify({ username, password }),\n"
"        })\n"
"          .then((response) => {\n"
"            // If the response status is ok, redirect to the dashboard\n"
"            if (response.ok) {\n"
"              window.location.href = \"http://192.168.50.140/dashboard\";\n"
"            } else {\n"
"              // Otherwise, display an error message\n"
"              alert(\"Invalid username or password\");\n"
"            }\n"
"          })\n"
"          .catch((error) => {\n"
"            console.error(error);\n"
"          });\n"
"      }\n"
"    </script>\n"
"  </body>\n"
"</html>\n"
;

char dashboard [] = "<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <title>Dashboard</title>\n"
"  <style>\n"
"    /* Body styles */\n"
"    body {\n"
"      font-family: Arial, sans-serif;\n"
"      margin: 0;\n"
"      padding: 0;\n"
"    }\n"
"    \n"
"    /* Sidebar styles */\n"
"    .sidebar {\n"
"      background-color: #222;\n"
"      color: #fff;\n"
"      height: 100%;\n"
"      position: fixed;\n"
"      width: 200px;\n"
"    }\n"
"    \n"
"    .sidebar h1 {\n"
"      color: #fff;\n"
"      margin: 20px;\n"
"    }\n"
"    \n"
"    .sidebar ul {\n"
"      list-style-type: none;\n"
"      margin: 0;\n"
"      padding: 0;\n"
"    }\n"
"    \n"
"    .sidebar li {\n"
"      margin: 10px 0;\n"
"      padding: 10px;\n"
"      text-align: center;\n"
"    }\n"
"    \n"
"    .sidebar li:hover {\n"
"      background-color: #333;\n"
"      cursor: pointer;\n"
"    }\n"
"    \n"
"    /* Content styles */\n"
"    .content {\n"
"      margin-left: 200px;\n"
"      padding: 20px;\n"
"    }\n"
"    \n"
"    /* Device configuration form styles */\n"
"    .form-container {\n"
"      background-color: #f2f2f2;\n"
"      padding: 20px;\n"
"    }\n"
"    \n"
"    .form-container label {\n"
"      display: block;\n"
"      margin-bottom: 10px;\n"
"    }\n"
"    \n"
"    .form-container input[type=text] {\n"
"      width: 100%;\n"
"      padding: 12px;\n"
"      border: 1px solid #ccc;\n"
"      border-radius: 4px;\n"
"      box-sizing: border-box;\n"
"      margin-bottom: 20px;\n"
"    }\n"
"    \n"
"    .form-container button {\n"
"      background-color: #4CAF50;\n"
"      color: white;\n"
"      padding: 12px 20px;\n"
"      border: none;\n"
"      border-radius: 4px;\n"
"      cursor: pointer;\n"
"    }\n"
"    \n"
"    .form-container button:hover {\n"
"      background-color: #45a049;\n"
"    }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"sidebar\">\n"
"    <h1>Menu</h1>\n"
"    <ul>\n"
"      <li onclick=\"getData('network')\">Network</li>\n"
"      <li onclick=\"openForm()\">Device Configurations</li>\n"
"      <li onclick=\"getData('enrollment')\">Enrollment</li>\n"
"      <li onclick=\"getData('date-time')\">Date & Time</li>\n"
"    </ul>\n"
"  </div>\n"
"  \n"
"  <div class=\"content\">\n"
"    <h2>Device Configurations</h2>\n"
"    <div class=\"form-popup\" id=\"myForm\">\n"
"      <form class=\"form-container\">\n"
"        <label for=\"device-id\">Device ID</label>\n"
"        <input type=\"text\" placeholder=\"Enter Device ID\" name=\"device-id\" required>\n"
"\n"
"        <label for=\"auth-token\">Auth Token</label>\n"
"        <input type=\"text\" placeholder=\"Enter Auth Token\" name=\"auth-token\" required>\n"
"\n"
"        <label for=\"device-location\">Device Location</label>\n"
"        <input type=\"text\" placeholder=\"Enter Device Location\" name=\"device-location\" required>\n"
"\n"
"        <button type=\"submit\" class=\"btn\">Save</button>\n"
"        <button type=\"button\" class=\"btn cancel\" onclick=\"closeForm()\">Close</button>\n"
"      </form>\n"
"    </div>\n"
"  </div>\n"
"  \n"
"  <script>\n"
"    // Open the device configuration form\n"
"    function openForm() {\n"
"      document.getElementById(\"myForm\").style.display = \"block\";\n"
"    }\n"
"    \n"
"    // Close the device configuration form\n"
"    function closeForm() {\n"
"      document.getElementById(\"myForm\").style.display =\n"
;